"""initial migration

Revision ID: 4b55e95f3ad5
Revises: 
Create Date: 2026-03-28 13:54:30.268268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b55e95f3ad5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slide_deck',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'WAITING_FOR_INPUT', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('current_thread_id', sa.String(), nullable=True),
    sa.Column('hitl_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_log', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slide_deck_created_at'), 'slide_deck', ['created_at'], unique=False)
    op.create_index(op.f('ix_slide_deck_id'), 'slide_deck', ['id'], unique=False)
    op.create_index(op.f('ix_slide_deck_user_id'), 'slide_deck', ['user_id'], unique=False)
    op.create_table('agent_snapshot',
    sa.Column('slide_deck_id', sa.UUID(), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['slide_deck_id'], ['slide_deck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_snapshot_created_at'), 'agent_snapshot', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_snapshot_id'), 'agent_snapshot', ['id'], unique=False)
    op.create_index(op.f('ix_agent_snapshot_slide_deck_id'), 'agent_snapshot', ['slide_deck_id'], unique=True)
    op.create_table('message',
    sa.Column('slide_deck_id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['slide_deck_id'], ['slide_deck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_created_at'), 'message', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_index(op.f('ix_message_slide_deck_id'), 'message', ['slide_deck_id'], unique=False)
    op.create_table('slide_deck_version',
    sa.Column('slide_deck_id', sa.UUID(), nullable=False),
    sa.Column('version_num', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('html_storage_path', sa.String(length=1000), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['slide_deck_id'], ['slide_deck.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slide_deck_id', 'version_num', name='uq_slide_deck_version')
    )
    op.create_index(op.f('ix_slide_deck_version_created_at'), 'slide_deck_version', ['created_at'], unique=False)
    op.create_index(op.f('ix_slide_deck_version_id'), 'slide_deck_version', ['id'], unique=False)
    op.create_index(op.f('ix_slide_deck_version_slide_deck_id'), 'slide_deck_version', ['slide_deck_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slide_deck_version_slide_deck_id'), table_name='slide_deck_version')
    op.drop_index(op.f('ix_slide_deck_version_id'), table_name='slide_deck_version')
    op.drop_index(op.f('ix_slide_deck_version_created_at'), table_name='slide_deck_version')
    op.drop_table('slide_deck_version')
    op.drop_index(op.f('ix_message_slide_deck_id'), table_name='message')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_index(op.f('ix_message_created_at'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_agent_snapshot_slide_deck_id'), table_name='agent_snapshot')
    op.drop_index(op.f('ix_agent_snapshot_id'), table_name='agent_snapshot')
    op.drop_index(op.f('ix_agent_snapshot_created_at'), table_name='agent_snapshot')
    op.drop_table('agent_snapshot')
    op.drop_index(op.f('ix_slide_deck_user_id'), table_name='slide_deck')
    op.drop_index(op.f('ix_slide_deck_id'), table_name='slide_deck')
    op.drop_index(op.f('ix_slide_deck_created_at'), table_name='slide_deck')
    op.drop_table('slide_deck')
    # ### end Alembic commands ###
